apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gatewayName }}
spec:
  gatewayClassName: {{ .Values.gatewayClassName }}
  listeners:
  - protocol: HTTP
    port: {{ .Values.openPort }}
    name: {{ .Values.openPortName }}
    allowedRoutes:
      namespaces:
        from: Same
