apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-route
spec:
  parentRefs:
  - name: {{ .Values.gatewayName }}
  rules:
  - backendRefs:
    - name: {{ .Release.Name }}-service-stable
      port: {{ .Values.openPort }}
      weight: {{ .Values.weights.stable }}
    - name: {{ .Release.Name }}-service-canary
      port: {{ .Values.openPort }}
      weight: {{ .Values.weights.canary }}