apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service-blue
spec:
  selector:
    app: {{ .Values.labelBlue.app | quote }}
  ports:
  - protocol: TCP
    port: {{ .Values.openPort }}
    targetPort: {{ .Values.targetPort.blue }}