#The name of the controller for GatewayClass object definition
controllerNameGatewayClass: istio.io/gateway-controller
gatewayName: gateway
gatewayClassName: istio-class

#Port on which Gateway Api listen to and also open port of services
openPort: 5000
openPortName: model-port-endpoint

#weights values for canary deployment release
weights:
  stable: 100
  canary: 0

#Deployments labels
labelStable: 
  app: yolo-stable
labelCanary: 
  app: yolo-canary

#Replica values for deployments
replicas:
  stable: 1
  canary: 1

#Container names
containerNames:
  stable: yolo-v3
  canary: yolo-v3

#Images names
image:
  stable: ghcr.io/mporada259449/yolo/yolo-v11:1.1
  canary: ghcr.io/mporada259449/yolo/yolo-v11:1.1

targetPort:
  stable: 5000
  canary: 5000

#limit resources for blue container
limits:
  stable:
    cpu: '2'
    memory: '2G'
  canary:
    cpu: '2'
    memory: '2G'

