#The name of the controller for GatewayClass object definition
controllerNameGatewayClass: istio.io/gateway-controller
gatewayName: gateway
gatewayClassName: istio-class
#Port on which Gateway Api listen to and also open port of services
openPort: 5000
openPortName: model-port-endpoint
#weights values for canary deployment release
weights:
  blue: 0
  green: 100
#Deployments labels
labelBlue:
  app: yolo-blue
labelGreen:
  app: yolo-green
#Replica values for deployments
replicas:
  blue: 1
  green: 1
#Container names
containerNames:
  blue: yolo-v3
  green: yolo-v3
#Images names
image:
  blue: ghcr.io/mporada259449/yolo/yolo-v11:1.1
  green: ghcr.io/mporada259449/yolo/yolo-v11:1.2
targetPort:
  blue: 5000
  green: 5000
targetPortTest: 5001
#limit resources for blue container
limits:
  blue:
    cpu: '2.5'
    memory: '4G'
  green:
    cpu: '2.5'
    memory: '4G'
