apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-route
spec:
  parentRefs:
  - name: {{ .Release.Name }}-gateway
  rules:
  - backendRefs:
    - name: {{ .Release.Name }}-service-blue
      port: {{ .Values.openPort }}
      weight: {{ .Values.weights.blue }}
    - name: {{ .Release.Name }}-service-green
      port: {{ .Values.openPort }}
      weight: {{ .Values.weights.green }}