name: 'YOLO container image building'

on:
  push:
    branches:
      - 'yolo-v**'
    paths:
    - 'model/**'
    - '.github/**'
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: yolo-model

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: "Cloning repository"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: "Setting variables"
        run: |
          echo "YOLO_FILE=$(jq -r '.YOLO_FILE' version.json)" >> $GITHUB_ENV
          echo "YOLO_VERSION=$(jq -r '.YOLO_VERSION' version.json)" >> $GITHUB_ENV
          echo "CONTAINER_VERSION=$(jq -r '.CONTAINER_VERSION' version.json)" >> $GITHUB_ENV

      - name: "Variables"
        run: |
          echo "YOLO_FILE=${{ env.YOLO_FILE }}"
          echo "YOLO_VERSION=${{ env.YOLO_VERSION }}"
          echo "CONTAINER_VERSION=${{ env.CONTAINER_VERSION }}"

      - name: "Logging into registry"
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: "Set image name"
        id: metadata
        uses: docker/metadata-action@v5
        with: 
          images: |
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository_owner }}/yolo/yolo-${{ env.YOLO_VERSION }}

      - name: "Build and push docker image"
        id: build
        uses: docker/build-push-action@v6
        with:
          context: model/
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository_owner }}/yolo/yolo-${{ env.YOLO_VERSION }}:${{ env.CONTAINER_VERSION }}
          build-args: |
            YOLO_FILE=${{ env.YOLO_FILE }}
          push: true

  tag:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: "Clone Repo"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      
      - name: "Setting variables"
        run: |
          echo "YOLO_FILE=$(jq -r '.YOLO_FILE' version.json)" >> $GITHUB_ENV
          echo "YOLO_VERSION=$(jq -r '.YOLO_VERSION' version.json)" >> $GITHUB_ENV
          echo "CONTAINER_VERSION=$(jq -r '.CONTAINER_VERSION' version.json)" >> $GITHUB_ENV
      
      - name: Tag commit
        run: |
          git config --global user.name ${{ github.repository_owner }}
          git config --global user.email 259449@student.pwr.edu.pl
          tag_name="${{ env.YOLO_VERSION }}.${{ env.CONTAINER_VERSION }}"
          git tag -a $tag_name -m "new image for version $tag_name" ${{ github.sha }}
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com//${{ github.repository }} $tag_name