name: "Test docker image building on pull request"

on:
  pull_request:
    branches:
      - master
    paths:
      - 'version.json'
      - 'model/**'
      - '.github/workflows/test-docker.yaml'
  workflow_dispatch:


jobs:
  run-test-script:
    runs-on: ubuntu-latest
    steps:
      - name: "Clone repo"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: "Prepare environments"
        run: |
          export YOLO_FILE=$(jq -r '.YOLO_FILE' version.json)
          export YOLO_VERSION=$(jq -r '.YOLO_VERSION' version.json)
          export CONTAINER_VERSION=$(jq -r '.CONTAINER_VERSION' version.json)
      
      - name: "Run test build"
        run: bash scripts/test-docker-build.sh
    
  check-new-version-file:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'model')
    steps:
      - name: "Check if version.json has been modified"
        run: |
          echo "To be done"

      




