name: "Test docker image building on pull request"

on:
  pull_request:
    branches:
      - master
    paths:
      - 'version.json'
      - 'model/**'
      - '.github/workflows/test-docker.yaml'
  workflow_dispatch:


jobs:
  check-new-version-file:
    runs-on: ubuntu-latest
#    if: ${{ contains(github.event.head_commit.modified, 'model') && ! contains(github.event.head_commit.modified, 'version.json') }}
    steps:
      - name: "Clone repo"
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: "Check if version.json has been modified"
        run: |
          git branch
          git diff --name-only HEAD^1 HEAD

  run-test-script:
    runs-on: ubuntu-latest
    steps:
      - name: "Clone repo"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: "Prepare environments"
        run: |
          echo "YOLO_FILE=$(jq -r '.YOLO_FILE' version.json)" >> $GITHUB_ENV
          echo "YOLO_VERSION=$(jq -r '.YOLO_VERSION' version.json)" >> $GITHUB_ENV
          echo "CONTAINER_VERSION=$(jq -r '.CONTAINER_VERSION' version.json)" >> $GITHUB_ENV
      
      - name: "Run test build"
        run: bash scripts/test-docker-build.sh
